### ISSUE TITLE
How to add custom font and custom google font in tailwind.js?

### ISSUE THREAD

**Issue by raunakhajela** [lazymozek/gulp-with-tailwindcss#1]
By default, tailwind allows certain fonts which you can use in your project in tailwind.js config file. I am trying to add custom font (e.g Gotham) and custom google font which is not available in the list to use in my project? Any ideas?

Can you test this out and share commit link if possible?

**Comment by manjumjn** [comment]
Actually, I was working on that. Will get back once I come up with an efficient solution :)

**Comment by manjumjn** [comment]
Here is the [Fix](https://github.com/manjumjn/gulp-with-tailwindcss/commit/afc3743fb09e9a0dd2180adf18b3b9c1b3cf150e) commit that seems to work for now.
