### ISSUE TITLE
Style's aren't loaded

### ISSUE THREAD

**Issue by KonradLinkowski** [lazymozek/gulp-with-tailwindcss#16]
It seems like the gulp doesn't work, probably wrong paths

I tried:
`npm install && npm run dev`

`npm run build` seems to not work either

![image](https://user-images.githubusercontent.com/26126510/103305089-9089a400-4a0a-11eb-831e-d31d36b07100.png)

Changing `../dist/css/style.css` to `./css/style.css` and `../dist/js/script.js` to `./js/script.js` fixes the issue

**Comment by manjumjn** [comment]
Yes, I have missed updating the paths on updating repo. 😁 Thanks

**Comment by manjumjn** [comment]
The path is correct. Actually I'm referring to the dev folder which is `dist` which will be created upon `npm run dev`
