### ISSUE TITLE
overriding custom classes with utility functions not working

### ISSUE THREAD

**Issue by markjohnson4** [lazymozek/gulp-with-tailwindcss#18]
Hi!  Thanks so much for creating this project!  An issue I encountered recently is when I create a custom class (ie ".btn" with @apply values) and then try to override it in the html later in a unique situation in my html (ie. "btn rounded-l-none"), Tailwind's utility classes like "rounded-l-none" are outputted *before* the custom classes like "btn".  So, in my example, "rounded-l-none" does nothing.

Tailwind's docs suggest putting custom classes `[between "components" and "utilities" ](https://tailwindcss.com/docs/installation#using-a-custom-css-file)` but I can't figure out how to do that here.

Can you help?  Thanks!

**Comment by markjohnson4** [comment]
Actually, I figured this out!  inside "partials", add a file "z.tailwinds.scss" and move the line "@tailwind utilities;" from "a.tailwinds.scss" to that file so it's read at the end.

**Comment by manjumjn** [comment]
yes, it's because of concatenation in gulp which takes in alphabetic order of filenames. I'm glad you figured it out :)
