### ISSUE TITLE
How to add more css file like AOS or anything else?

### ISSUE THREAD

**Issue by themeix** [lazymozek/gulp-with-tailwindcss#29]
Can you please show an example, how to include more extra css file in there?

And also please show the ideal method to include new js like jquery, owl-carousel etc.

Thanks

**Comment by manwithawp** [comment]
In a.tailwind.scss for example swiper
```

@tailwind base;
@tailwind components;
@tailwind utilities;

@import "../../node_modules/swiper/swiper-bundle";  
```
