### ISSUE TITLE
Please add a license

### ISSUE THREAD

**Issue by rootwork** [lazymozek/gulp-with-tailwindcss#32]
Hi,

This is a great starter project, but there's no license included. Technically speaking, your code isn't currently open-sourced and people can't freely use it or build upon it. More info:

https://opensource.stackexchange.com/questions/1720/what-can-i-assume-if-a-publicly-published-project-has-no-license#1721

I don't want to presume to choose a license for you, or I'd submit this as a pull-request, but here's GitHub's guide:

https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-license-to-a-repository

MIT is common; I've also used GPL3 and AGPL3 quite a bit.

Thanks for your work on this and for considering adding this!

**Comment by manjumjn** [comment]
I'll create new repo with license. This repo will be archived.
