### ISSUE TITLE
npm run dev | error

### ISSUE THREAD

**Issue by ag-77** [lazymozek/gulp-with-tailwindcss#44]
Hi,

I just downloaded this gulp+tailwind project. Followed all instructions and "npm run dev" command trows an error.

Is something incorrectly done from my side? Can someone assist me with - how to fix this issue?

Screenshot attached for your reference.

I would appreciate any hint or guidance.

Thanks 
<img width="1680" alt="Error-1" src="https://user-images.githubusercontent.com/34688239/211166401-b03f58db-a0c4-4729-a9e6-a164c73e2a04.png">

**Comment by ag-77** [comment]
I solved it - created folder by name "dist" in project folder and "npm run dev" command works.

**Comment by manjumjn** [comment]
Hey @ag-77 yes i think it’s searching for folder which doesn’t exist on initial run. I’ll push a fix. Thanks
